# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climate_Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Frame_Products_Join_Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_light_transmission', models.IntegerField(default=0)),
                ('visible_light_reflect', models.IntegerField(default=0)),
                ('solar_energy_total_elimination', models.IntegerField(default=0)),
                ('solar_energy_reflect', models.IntegerField(default=0)),
                ('solar_energy_absorption', models.IntegerField(default=0)),
                ('solar_energy_direct_transmission', models.IntegerField(default=0)),
                ('IGDB_SHGC', models.FloatField(default=0)),
                ('system_U_value_alum_steel', models.FloatField(default=0)),
                ('system_U_value_timber_uPVC_alumn_thermally_broken', models.FloatField(default=0)),
                ('primadoor_tested_SHGC', models.FloatField(default=0)),
                ('primadoor_tested_U_value', models.FloatField(default=0)),
                ('Shading_coefficient', models.FloatField(default=0)),
                ('UV_elimination', models.FloatField(default=0)),
                ('noise_control', models.IntegerField(default=0)),
                ('safety_rating', models.IntegerField(default=0)),
                ('security_rating', models.IntegerField(default=0)),
                ('frame_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glazing.Frame')),
            ],
        ),
        migrations.CreateModel(
            name='Glazing_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('floor_number', models.IntegerField(default=1)),
                ('nett_floor_area', models.IntegerField(default=1)),
                ('conductance_constant', models.FloatField(default=0)),
                ('CSHGC', models.FloatField(default=0)),
                ('climate_zone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glazing.Climate_Zone')),
            ],
        ),
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('category', models.IntegerField(default=1)),
                ('product_range', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Windows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('shading_p', models.FloatField(default=0)),
                ('shading_h', models.FloatField(default=0)),
                ('window_area', models.FloatField(default=0)),
                ('ph', models.FloatField(default=0)),
                ('solar_exposure', models.FloatField(default=0)),
                ('shgc_glazing', models.FloatField(default=0)),
                ('shgc_proposed', models.FloatField(default=0)),
                ('u_value', models.FloatField(default=0)),
                ('conductance', models.FloatField(default=0)),
                ('glazing_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glazing.Glazing_Project')),
                ('orientation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glazing.Orientation')),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glazing.Products')),
            ],
        ),
        migrations.AddField(
            model_name='frame_products_join_tbl',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glazing.Products'),
        ),
    ]
