# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glazing', '0002_auto_20161112_0929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Glass',
        ),
        migrations.RenameModel(
            old_name='Product_Category',
            new_name='Glass_Category',
        ),
        migrations.RenameField(
            model_name='windows',
            old_name='products_id',
            new_name='glass_id',
        ),
    ]
