# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glazing', '0003_auto_20161112_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='windows',
            name='frame_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='glazing.Frame'),
            preserve_default=False,
        ),
    ]
