# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glazing', '0004_windows_frame_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solar_Exposure_Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=200)),
                ('ph', models.FloatField(default=0)),
                ('e', models.FloatField(default=0)),
            ],
        ),
    ]
