# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glazing', '0005_solar_exposure_factor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solar_exposure_factor',
            options={'verbose_name': 'Solar Exposure Factor', 'verbose_name_plural': 'Solar Exposure Factors'},
        ),
        migrations.AddField(
            model_name='orientation',
            name='symbol',
            field=models.CharField(default='N', max_length=200),
            preserve_default=False,
        ),
    ]
