# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glazing', '0006_auto_20161113_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='solar_exposure_factor',
            name='orientation',
            field=models.CharField(default='N', max_length=200),
            preserve_default=False,
        ),
    ]
