# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glazing', '0007_solar_exposure_factor_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='climate_zone',
            name='interior',
            field=models.CharField(default='hot', max_length=200),
            preserve_default=False,
        ),
    ]
