# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glazing', '0009_auto_20161113_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solar_exposure_factor',
            name='orientation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glazing.Orientation'),
        ),
        migrations.AlterField(
            model_name='solar_exposure_factor',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glazing.Climate_Zone'),
        ),
    ]
