# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glazing', '0010_auto_20161113_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windows',
            name='solar_exposure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glazing.Solar_Exposure_Factor'),
        ),
    ]
