# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glazing', '0011_auto_20161113_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climate_zone',
            options={'verbose_name': 'Climate Zone', 'verbose_name_plural': 'Climate Zones'},
        ),
        migrations.AlterModelOptions(
            name='windows',
            options={'verbose_name': 'Window', 'verbose_name_plural': 'Windows'},
        ),
        migrations.AlterField(
            model_name='windows',
            name='solar_exposure',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='glazing.Solar_Exposure_Factor'),
        ),
    ]
