# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glazing', '0012_auto_20161113_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='SHGC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frame',
            name='U',
            field=models.IntegerField(default=0),
        ),
    ]
