# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glazing', '0014_auto_20161113_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHGC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SHGC', models.FloatField(default=0)),
                ('frame_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glazing.Frame')),
            ],
            options={
                'verbose_name': 'Frame/Glass SHGC',
                'verbose_name_plural': 'Frame/Glass SHGC',
            },
        ),
        migrations.CreateModel(
            name='U_Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_value', models.FloatField(default=0)),
                ('frame_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glazing.Frame')),
            ],
            options={
                'verbose_name': 'Frame/Glass U-value',
                'verbose_name_plural': 'Frame/Glass U-values',
            },
        ),
        migrations.RemoveField(
            model_name='frame_products_join_tbl',
            name='frame_id',
        ),
        migrations.RemoveField(
            model_name='frame_products_join_tbl',
            name='product_id',
        ),
        migrations.AlterModelOptions(
            name='glass',
            options={'verbose_name': 'Glass Product', 'verbose_name_plural': 'Glass Products'},
        ),
        migrations.AlterModelOptions(
            name='glass_category',
            options={'verbose_name': 'Glass Product Category', 'verbose_name_plural': 'Glass Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='glazing_project',
            options={'verbose_name': 'Glazing Project', 'verbose_name_plural': 'Glazing Projects'},
        ),
        migrations.DeleteModel(
            name='Frame_Products_Join_Tbl',
        ),
        migrations.AddField(
            model_name='u_value',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glazing.Glass'),
        ),
        migrations.AddField(
            model_name='shgc',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glazing.Glass'),
        ),
    ]
