# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glazing', '0016_auto_20161113_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glass_frame_join',
            old_name='frame_id',
            new_name='frame',
        ),
        migrations.RenameField(
            model_name='glass_frame_join',
            old_name='product_id',
            new_name='glass',
        ),
        migrations.RemoveField(
            model_name='windows',
            name='shgc_glazing',
        ),
        migrations.RemoveField(
            model_name='windows',
            name='u_value',
        ),
        migrations.AddField(
            model_name='windows',
            name='glass_frame_join',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='glazing.Glass_Frame_Join'),
        ),
    ]
