# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glazing', '0017_auto_20161113_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glazing_project',
            name='CSHGC',
        ),
        migrations.RemoveField(
            model_name='glazing_project',
            name='conductance_constant',
        ),
    ]
