# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glazing', '0022_auto_20161221_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='user_id',
        ),
    ]
