# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glazing', '0023_auto_20161221_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='glazing_project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
